### ISSUE TITLE
error for automatic detection of .db files from the directory

### ISSUE THREAD

**Issue by Ekie22** [lebsnu/ezaai#12]
Hallo,
 I want to calculate AAI values and use as input just the directory with the profile DBs (db/) as shown in the tutorial
```
java -jar ~/bin/EzAAI.jar  calculate -i db/ -j db/ -o aai_out/test.tsv
```
However, I get the following error:

EzAAI - v1.2 [Mar. 2022]
java.io.FileNotFoundException: mm.label (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at leb.main.EzAAI.runCalculate(EzAAI.java:307)
	at leb.main.EzAAI.run(EzAAI.java:482)
	at leb.main.EzAAI.main(EzAAI.java:517)

I also tried it with "db/*.db" but than just the selfcomparison of the first db file is calculated.
MMseqs2 Version: 13.45111

Thanks

**Comment by endix1029** [comment]
Hi, would you please run the same command using `-dev` option and post the full log here?

The command you should run will be:

```
java -jar ~/bin/EzAAI.jar calculate -i db/ -j db/ -o aai_out/test.tsv -dev
```

Thanks!

**Comment by Ekie22** [comment]
Hi, with the command output I recognized the problem. Within the db/ folder I had a subfolder where I stored db files. It seems that the program tries to use this subfolder:
… 
[MAR 16 08:36:38] DEV     |:  exec: tar -x -z -f /ezAAI/db/storage
[MAR 16 08:36:38] DEV     |:  exec: /bin/bash -c mmseqs convert2fasta mm /tmp/1a4693815e80be43_faa/i2.faa
java.io.FileNotFoundException: mm.label (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at leb.main.EzAAI.runCalculate(EzAAI.java:307)
	at leb.main.EzAAI.run(EzAAI.java:482)
	at leb.main.EzAAI.main(EzAAI.java:517)
[MAR 16 08:36:38] ERROR   |:  Program terminated with error.

After I moved the subfolder to another location the program ran without trouble.
Thanks

**Comment by endix1029** [comment]
Ah yes. Currently the program does not allow any other files/directories to be present within the input directory.
I will consider to develop an automated detection feature that can make the program exclusively use the database files only.

Thank you for sharing your experience!
