### ISSUE TITLE
Calculating AAI fails with PGAP annotated genomes

### ISSUE THREAD

**Issue by ak-watson** [lebsnu/ezaai#3]
I was trying to use EzAai with genomes that had already annotated using pgap (extracting the database from an existing ".faa" file).

Creating the database with convert from the .faa file runs without errors.

The "calculate" run fails with the following error. 

`JUL 12 15:30:41] EzAAI   |:  Calculating AAI... [Task 1/1]
[JUL 12 15:30:41] EzAAI   |:  Preparing to run reciprocal MMSeqs2 search...
[JUL 12 15:30:41] EzAAI   |:  Running MMSeqs2 search... (/tmp/5099f44642a78a35_faa/i0.faa vs. /tmp/5099f44642a78a35_faa/j0.faa)
[JUL 12 15:30:45] EzAAI   |:  Running MMSeqs2 search... (/tmp/5099f44642a78a35_faa/j0.faa vs. /tmp/5099f44642a78a35_faa/i0.faa)
java.lang.NullPointerException
	at leb.process.ProcCalcPairwiseAAI.calcIdentityWithDetails(ProcCalcPairwiseAAI.java:363)
	at leb.process.ProcCalcPairwiseAAI.pairwiseMmseqs(ProcCalcPairwiseAAI.java:568)
	at leb.process.ProcCalcPairwiseAAI.calculateProteomePairWithDetails(ProcCalcPairwiseAAI.java:243)
	at leb.main.EzAAI.runCalculate(EzAAI.java:313)
	at leb.main.EzAAI.run(EzAAI.java:445)
	at leb.main.EzAAI.main(EzAAI.java:480)
`

Taking the genomes and using "extract" to run prodigal gene annotation to produce the .db file works as expected.

Maybe there is some characters in the pgap fasta headers that EzAai doesn't like?

Thanks,
Andrew

**Comment by endix1029** [comment]
Sorry for the way delayed response.

Unfortunately it is impossible for me to figure out the exact reason that occurred the error without the data that caused such problem.

I will be much appreciated if you are able to send me a PGAP FASTA file, or any sort of toy example of PGAP outcomes, which is causing such problem.

Thanks!
