### ISSUE TITLE
AAI calculation error

### ISSUE THREAD

**Issue by pkstranger** [lebsnu/ezaai#4]
I am trying to calculate AAI using EZAAI. I have already created the DB file from genome but when executing command for AAI calculation, programme is terminated in between. Below is the screenshot for same.
$ java -jar EzAAI_latest.jar calculate -i db/ -j db/ -o out/SAOS_164_21_8_21.tsv 
[AUG 21 14:09:44] EzAAI   |:  EzAAI - v1.0 [Mar. 2021]
[AUG 21 14:09:47] EzAAI   |:  Calculating AAI... [Task 1/1600]
[AUG 21 14:09:59] EzAAI   |:  Calculating AAI... [Task 2/1600]
[AUG 21 14:10:09] EzAAI   |:  Calculating AAI... [Task 3/1600]
[AUG 21 14:10:21] EzAAI   |:  Calculating AAI... [Task 4/1600]
[AUG 21 14:10:32] EzAAI   |:  Calculating AAI... [Task 5/1600]
[AUG 21 14:10:44] EzAAI   |:  Calculating AAI... [Task 6/1600]
[AUG 21 14:10:55] EzAAI   |:  Calculating AAI... [Task 7/1600]
[AUG 21 14:11:05] EzAAI   |:  Calculating AAI... [Task 8/1600]
[AUG 21 14:11:16] EzAAI   |:  Calculating AAI... [Task 9/1600]
java.lang.NullPointerException
	at leb.process.ProcCalcPairwiseAAI.calcIdentityWithDetails(ProcCalcPairwiseAAI.java:364)
	at leb.process.ProcCalcPairwiseAAI.pairwiseMmseqs(ProcCalcPairwiseAAI.java:568)
	at leb.process.ProcCalcPairwiseAAI.calculateProteomePairWithDetails(ProcCalcPairwiseAAI.java:243)
	at leb.main.EzAAI.runCalculate(EzAAI.java:313)
	at leb.main.EzAAI.run(EzAAI.java:445)
	at leb.main.EzAAI.main(EzAAI.java:480)
[AUG 21 14:11:26] ERROR   |:  Program terminated with error.

**Comment by zhangqm28** [comment]
Hi,
I have the same error as your. Did you solve it?

**Comment by pkstranger** [comment]
> Hi, I have the same error as your. Did you solve it?

Yes, actually one of my genomes was corrupted. I have redownloaded the sequence and run the command afterward I got the result.

**Comment by agg437** [comment]
Hi, I also got the same error, how did you find out which genomes were corrupted? did you use prokka .fna files ?

> I am trying to calculate AAI using EZAAI. I have already created the DB file from genome but when executing command for AAI calculation, programme is terminated in between. Below is the screenshot for same. $ java -jar EzAAI_latest.jar calculate -i db/ -j db/ -o out/SAOS_164_21_8_21.tsv [AUG 21 14:09:44] EzAAI |: EzAAI - v1.0 [Mar. 2021] [AUG 21 14:09:47] EzAAI |: Calculating AAI... [Task 1/1600] [AUG 21 14:09:59] EzAAI |: Calculating AAI... [Task 2/1600] [AUG 21 14:10:09] EzAAI |: Calculating AAI... [Task 3/1600] [AUG 21 14:10:21] EzAAI |: Calculating AAI... [Task 4/1600] [AUG 21 14:10:32] EzAAI |: Calculating AAI... [Task 5/1600] [AUG 21 14:10:44] EzAAI |: Calculating AAI... [Task 6/1600] [AUG 21 14:10:55] EzAAI |: Calculating AAI... [Task 7/1600] [AUG 21 14:11:05] EzAAI |: Calculating AAI... [Task 8/1600] [AUG 21 14:11:16] EzAAI |: Calculating AAI... [Task 9/1600] java.lang.NullPointerException at leb.process.ProcCalcPairwiseAAI.calcIdentityWithDetails(ProcCalcPairwiseAAI.java:364) at leb.process.ProcCalcPairwiseAAI.pairwiseMmseqs(ProcCalcPairwiseAAI.java:568) at leb.process.ProcCalcPairwiseAAI.calculateProteomePairWithDetails(ProcCalcPairwiseAAI.java:243) at leb.main.EzAAI.runCalculate(EzAAI.java:313) at leb.main.EzAAI.run(EzAAI.java:445) at leb.main.EzAAI.main(EzAAI.java:480) [AUG 21 14:11:26] ERROR |: Program terminated with error.

**Comment by kellikmullane** [comment]
I had this exact same issue and realized all of the files created from the 'extract' module were corrupted. I thought perhaps it was my sequence files so I downloaded the sample dataset from the EzAAI tutorial and ran the code exactly as it is on the tutorial. All of the .db files are corrupted and I get the same error. This seems to be some type of compatibility issue with EzAAI and certain machines. For reference I am running on MacOS v12.6

Hoping the creators of EzAAI have a suggestion on how to resolve this issue?

**Comment by endixk** [comment]
Hello @kellikmullane, could you please attach the corrupted `.db` file from the tutorial set here for us to examine?

**Comment by kellikmullane** [comment]
@endixk thanks for replying! In order to attach it here, I had to convert it to a .txt file. But I will email you the .db file as well in case the conversion changes something. I ran all of the code exactly the same with the exception that I did not use the -l flag, as I wasn't sure what it did (couldn't find a description of this feature anywhere in the documentation). 

[my_example_db.txt](https://github.com/endixk/ezaai/files/9974532/my_example_db.txt)

**Comment by kellikmullane** [comment]
Hey Daniel,
Here's the .db file!

Best,
Kelli

----
Kelli Mullane, M.S. (she/her/hers)
Ph.D. Candidate
Bartlett Lab, Marine Biology
Scripps Institution of OceanographyUniversity of California, San Diego


 

    On Tuesday, November 8, 2022 at 09:04:29 PM PST, Daniel DW Kim ***@***.***> wrote:  
 
 


Hello @kellikmullane, could you please attach the corrupted .db file from the tutorial set here for us to examine?

**Comment by endixk** [comment]
Thank you for your swift response! `.txt` file is broken as expected. I also received the mail but I guess the attachment was removed during the transmission. Could you please upload it as a `.zip` file by compressing it?

**Comment by kellikmullane** [comment]
Hopefully this works...
[my_example_db.db.zip](https://github.com/endixk/ezaai/files/9993735/my_example_db.db.zip)

**Comment by endixk** [comment]
Hey Kelli, I examined your DB file and found that the file is modified by SQLite-related program:

```
$ head my_example_db.db
SQLite format 3@  ���._��������!�P��,L�fD}"
�4�`*���R
```

However, the DB file generated by `extract` module is simply a renamed `tar.gz` file, which should not contain any sort of SQLite metadata. My assumption is that the file has been automatically modified by an external DBMS program, which made file unrecognizable by the `calculate` module.

**Comment by mau-olvera** [comment]
I have the same problem but the extract function made all my genomes unrecognizable, what can I do?
